name: rusty_2
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - mcp
  - openai
  - requests
  - streamlit
  - fastapi
  - uvicorn
  - pip:
    - mcp-server-git
    - pytest
    - pylint

